const description = [
  "Super Micro Computer is a global leader in high-performance, high-efficiency server technology and innovation.",
  "Gigacloud Technology focuses on providing cutting-edge solutions in the cloud computing industry, offering services and technologies to enhance digital operations.",
  "Carvana is an online platform that simplifies the process of buying and selling used cars, providing a seamless and transparent car buying experience.",
  "Abercrombie & Fitch is a global specialty retailer known for its trendy and casual apparel, targeting a young demographic.",
  "Macrogenics is a biopharmaceutical company dedicated to discovering and developing innovative antibody-based therapies for the treatment of cancer.",
  "Tourmaline Bio is a biotech company focused on advancing novel therapies to address unmet medical needs, particularly in the field of oncology.",
  "C S P Inc is engaged in manufacturing and supplying engineered materials and products, serving diverse industries such as automotive, electronics, and more.",
  "Cymabay Therapeutics is a biopharmaceutical company developing therapies for liver and metabolic diseases, with a focus on innovation and patient well-being.",
  "American Coastal Insurance Corp is involved in providing insurance solutions, specializing in coastal and high-risk areas.",
  "Carrols Restaurant Group is one of the largest restaurant franchisees in the United States, operating popular fast-food chains.",
  "Rxsight Inc focuses on developing innovative medical devices for the improvement of vision and eye care.",
  "Soleno Therapeutics is a biopharmaceutical company dedicated to the development and commercialization of novel therapeutics for rare diseases.",
  "Groupon is an e-commerce platform that offers discounts and deals on various products and services, connecting consumers with local businesses.",
  "Alpine Immune Sciences focuses on discovering and developing innovative immunotherapies for the treatment of various diseases.",
  "Vertiv Holdings provides critical digital infrastructure technologies and solutions, ensuring the reliability and efficiency of vital systems.",
  "Modine Manufacturing is a global leader in thermal management solutions, designing and manufacturing heating and cooling systems for various industries.",
  "Nvidia is a leading technology company known for its graphics processing units (GPUs) and AI technologies, playing a key role in the gaming, automotive, and data center industries.",
  "Lifemd Inc is a healthcare technology company that focuses on providing innovative solutions for personalized and accessible healthcare services.",
  "Applovin is a mobile app technology company that specializes in marketing, analytics, and monetization solutions for app developers.",
  "Neuropace Inc develops and manufactures medical devices for the treatment of neurological disorders, with a focus on responsive neurostimulation.",
  "Immunome Inc is a biotech company dedicated to discovering and developing antibody-based therapies for infectious diseases and cancer.",
  "Celestica Inc is a global electronics manufacturing services company, providing a range of design, manufacturing, and supply chain solutions.",
  "Xpo Inc is a global logistics company offering supply chain solutions, transportation, and logistics services to businesses worldwide.",
  "Alarum Technologies is listed without a specific industry, and additional information is needed to provide a specific description of the company's activities.",
  "Jin Medical International Ltd is likely involved in the healthcare industry, and specific activities may include medical research, technology, or other healthcare-related services.",
  "Y-Mabs Therapeutics is a biopharmaceutical company focused on developing novel antibody-based therapies for the treatment of pediatric cancers.",
  "NN Inc is a diversified industrial company providing high-precision metal and plastic components and assemblies for various industries.",
  "Skywest Inc is a regional airline company providing scheduled passenger and air freight services to destinations in North America.",
  "Mereo Biopharma Group is a biotech company dedicated to developing innovative therapies for rare and specialty diseases.",
  "Merus N.V. is a clinical-stage immuno-oncology company focused on developing innovative bispecific antibody therapeutics for cancer treatment.",
  "Centessa Pharmaceuticals is a biopharmaceutical company focused on creating a diversified portfolio of innovative therapies through a collaborative approach.",
  "Ideaya Biosciences is a biotech company specializing in the discovery and development of synthetic lethality-based precision medicines for oncology.",
  "Crowdstrike Holdings is a cybersecurity company that provides cloud-delivered endpoint protection solutions to detect and prevent cyber threats.",
  "Dave Inc is a financial technology company that offers various services, including budgeting tools, financial insights, and payday advance features.",
  "Meta Platforms Inc, formerly known as Facebook, is a global technology company that owns and operates popular social media platforms and services.",
  "Werewolf Therapeutics is a biotech company focused on developing novel immunomodulatory therapies for cancer treatment.",
  "Dream Finders Homes is a homebuilding company that designs and constructs homes, with a focus on providing innovative and quality housing solutions.",
  "Camtek Ltd is a technology company specializing in developing and manufacturing inspection and metrology equipment for the semiconductor industry.",
  "Bimi Intl Medical Inc is involved in the medical equipment industry, and their activities may include the development and distribution of medical devices.",
  "Limbach Holdings Inc is a company in the construction and engineering industry, providing a range of services such as HVAC, plumbing, and electrical solutions.",
  "Talkspace Inc is a telehealth platform that offers online therapy and mental health services, connecting individuals with licensed therapists.",
  "Nephros Inc is a medical device company focused on developing and commercializing products for improving water quality in healthcare and industrial settings.",
  "Alpha Metallurgical Resources Inc is a mining company engaged in the exploration, development, and production of metallurgical coal.",
  "Smith-Midland Corp is a construction company specializing in precast concrete products, including barriers, sound walls, and other infrastructure components.",
  "Iperionx Limited is listed without a specific industry, and additional information is needed to provide a specific description of the company's activities.",
  "Mersana Therapeutics is a biopharmaceutical company focused on developing antibody-drug conjugates (ADCs) for the treatment of cancer.",
  "Ies Holdings is an electrical contracting company providing a range of services, including electrical systems design, installation, and maintenance.",
  "M-Tron Industries Inc is a company in the electronic components industry, possibly involved in the manufacturing and distribution of electronic parts.",
  "E.L.F. Beauty Inc is a cosmetics company that offers a range of affordable and cruelty-free beauty products, catering to a diverse consumer base.",
  "Crexendo Inc is a cloud communications company providing business communication and collaboration solutions, including VoIP and cloud-based services.",
  "Pharvaris N.V. is a biopharmaceutical company focused on the development of novel therapies for rare diseases, particularly in the field of inflammation.",
  "Repositrak Inc is a technology company that offers solutions for supply chain visibility, compliance, and risk management, with a focus on the food industry.",
  "Neurogene Inc is a biotech company dedicated to developing gene therapies for the treatment of neurogenetic diseases.",
  "Asp Isotopes Inc is involved in the pharmaceutical industry, and their activities may include the development and production of isotopes for medical and research purposes.",
  "Rover Group Inc is a technology platform connecting pet owners with pet care services, including pet sitting, dog walking, and boarding.",
  "Amneal Pharmaceuticals Inc is a pharmaceutical company focused on the development, manufacturing, and distribution of generic and specialty pharmaceuticals.",
  "Codere Online Luxembourg S.A. is involved in the online gambling industry, providing digital gaming and betting services.",
  "Vera Therapeutics Inc is a biopharmaceutical company focused on developing therapies for patients with serious immunological diseases.",
  "Pulse Biosciences is a biotech company specializing in the development of novel medical devices for the treatment of cancer and other skin conditions.",
  "Nuvalent Inc is a biopharmaceutical company dedicated to discovering and developing targeted therapies for patients with cancer.",
  "Powell Industries Inc is a company in the electrical equipment industry, providing solutions for the control, distribution, and management of electrical energy.",
  "Oric Pharmaceuticals Inc is a biotech company focused on developing innovative therapies for the treatment of cancer, with a focus on overcoming resistance.",
  "Uber Technologies Inc is a technology company that operates a ridesharing platform, connecting users with transportation services through a mobile app.",
  "Microstrategy Inc is a business intelligence company that provides software solutions for analytics, mobility, and security, empowering organizations with data-driven insights.",
  "Ambrx Biopharma Inc is a biotech company engaged in the discovery and development of biotherapeutics, including protein therapeutics and antibody-drug conjugates.",
  "New Oriental Education & Technology Group is a leading educational company providing a range of educational services, including language training and test preparation.",
  "Biohaven Ltd is a biopharmaceutical company focused on developing and commercializing innovative therapies for neurological and neuropsychiatric diseases.",
  "Cabaletta Bio Inc is a biopharmaceutical company specializing in the development of T cell therapies for the treatment of B cell-mediated autoimmune diseases.",
  "Byrna Technologies Inc is a company in the defense industry, specializing in the development and manufacturing of non-lethal personal security devices.",
  "Silence Therapeutics is a biotech company focused on developing RNA interference (RNAi) therapies for the treatment of genetic disorders and diseases.",
  "T A T Tech Ltd is likely involved in the transportation industry, and specific activities may include providing technology solutions for the transportation sector.",
  "Ftai Aviation Ltd is involved in the aviation and transportation industry, and their activities may include leasing and managing aircraft.",
  "Eli Lilly and Company is a global pharmaceutical company that develops and manufactures a wide range of pharmaceutical products for various therapeutic areas.",
  "Ultrapar Participacoes S.A. is a Brazilian company engaged in the distribution of fuel, production of petrochemicals, and other energy-related activities.",
  "Tarsus Pharmaceuticals Inc is a biopharmaceutical company focused on developing therapies for inflammatory and fibrotic diseases.",
  "Brainsway Ltd is a medical device company that specializes in the development and commercialization of non-invasive brain stimulation technologies for various neuropsychiatric disorders.",
  "Safety Shot Inc is a technology company likely focused on safety solutions, and their activities may include the development of safety-related products or technologies.",
  "Makemytrip Ltd is an online travel company that provides a platform for booking flights, hotels, and holiday packages, catering to travelers in India and other markets.",
  "Nutanix Inc is a technology company that offers cloud computing and hyper-converged infrastructure solutions, simplifying IT operations for businesses.",
  "Cimpress N.V. is a company in the printing and marketing industry, providing customized products and services for businesses and individuals.",
  "Universal Technical Institute Inc is an educational institution that specializes in providing training programs for students seeking careers in the automotive and transportation industries.",
  "Builders Firstsource is a leading supplier of building materials, providing a wide range of products and services to the residential construction and remodeling industries.",
  "Advanced Micro Devices (AMD) is a semiconductor company that designs and manufactures high-performance computing and graphics solutions for a variety of applications.",
  "Spotify Technology S.A. is a leading music streaming platform, providing users with access to a vast library of music, podcasts, and other audio content.",
  "Installed Building Products is a company that specializes in the installation of insulation and other building products, serving the residential and commercial construction markets.",
  "Blueprint Medicines Corp is a biopharmaceutical company focused on developing precision therapies for patients with genomically defined diseases.",
  "Vistra Energy Corp is an integrated energy company that generates and sells electricity, serving both residential and commercial customers.",
  "Coinbase Global Inc is a leading cryptocurrency exchange platform, providing a secure and user-friendly platform for buying, selling, and storing various cryptocurrencies.",
  "Deckers Outdoor Corp is a global footwear and apparel company known for its brands such as UGG, Teva, and HOKA ONE ONE, offering a range of outdoor and casual products.",
  "Viking Therapeutics is a biopharmaceutical company focused on the development of novel therapies for metabolic and endocrine disorders.",
  "Real Brokerage Inc is a technology-driven real estate brokerage company that leverages digital platforms to connect real estate agents with clients.",
  "Abeona Therapeutics is a biopharmaceutical company dedicated to developing gene and cell therapies for patients with rare genetic diseases.",
  "Third Harmonic Bio Inc is a biotech company focused on developing therapies for the treatment of cancer and other diseases through precision medicine approaches.",
  "Summit Therapeutics is a biopharmaceutical company working on the discovery and development of novel therapies for genetic and infectious diseases.",
  "Orion Group Holdings Inc is a construction company providing a range of services in the marine and industrial sectors, including infrastructure and waterfront projects.",
  "Applied Therapeutics Inc is a biopharmaceutical company focused on developing novel therapies for the treatment of cardiovascular and metabolic diseases.",
  "Medpace Holdings Inc is a clinical research organization (CRO) providing research and development services to the pharmaceutical and biotechnology industries.",
  "Ardelyx Inc is a biotech company engaged in the discovery and development of innovative therapies for the treatment of gastrointestinal and cardiorenal diseases.",
  "Broadcom Ltd is a global technology company specializing in the development and supply of a broad range of semiconductor and infrastructure software solutions.",
  "Mama's Creations Inc is listed without a specified industry, and additional information is needed to provide a specific description of the company's activities.",
];

const profile = () => {
  const profiles = [],
    comments = [];
  for (let i = 0; i < 10; i++) {
    profiles.push({ user_id: 1, stock_id: i * 2 + 1 });
    comments.push({
      user_id: 1,
      stock_id: i * 2 + 1,
      message: `Decent stock...`,
      username: "andrew123",
    });
  }
  for (let i = 0; i < 3; i++) {
    profiles.push({ user_id: 2, stock_id: i * 3 + 1 });
    comments.push({
      user_id: 2,
      stock_id: i * 3 + 1,
      message: `Apes strong together`,
      username: "andrew1234",
    });
  }
  return { profiles, comments };
};

module.exports = { description, profile };
